# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "pot-unstable-${version}";
  version = "2020-06-14";
  rev = "caac6bd5f7ee760a22db5439bdecd4b14829798d";

  goPackagePath = "github.com/SeungheonOh/pot";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/SeungheonOh/pot";
    sha256 = "0mm623k7fa2zdyd9a0ik8fqcxq2xngr4m5kl0dnk68id32fz3dws";
  };

  goDeps = [
    {
      goPackagePath = "golang.org/x/crypto";
      fetch = {
        type = "git";
        url = "https://go.googlesource.com/crypto";
        rev = "056763e48d71961566155f089ac0f02f1dda9b5a";
        sha256 = "0dcmns62hwid7hk4bmpl22z6ygjh168p23x3arzy320sd1lvap92";
      };
    }
    {
      goPackagePath = "golang.org/x/sys";
      fetch = {
        type = "git";
        url = "https://go.googlesource.com/sys";
        rev = "59c9f1ba88faf592b225274f69c5ef1e4ebacf82";
        sha256 = "014iiqjh9sikbcvacqiwhg6mvrsrr1va91wmc9yrnsm11c63yxfa";
      };
    }
  ];

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}