syntax on
highlight Comment cterm=italic
highlight String cterm=italic
highlight Constant cterm=bold,italic
set softtabstop=2 tabstop=2 shiftwidth=2 expandtab
set smarttab
set nu
set autoindent
set ruler
set encoding=UTF-8
set noshowmode
set mouse=a
let mapleader=" "

nnoremap <leader>// :let @/ = ""<cr>
map <F1> "+p
imap <F1> <ESC>"+pi
map <F2> "+y
nnoremap <F3> gg"+yG

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

filetype plugin on
call plug#begin('~/.config/nvim/plugged')
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'LnL7/vim-nix'
call plug#end()

if has("nvim")
  au TermOpen * tnoremap <Esc> <c-\><c-n>
  au FileType fzf tunmap <Esc>
endif

nnoremap NT :NERDTreeToggle<cr>
nnoremap <leader>nt :NERDTreeToggle<cr>
nnoremap <leader>ff :FZF <cr>
nnoremap <leader>ag :Ag<cr>
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)